service:
  name: serverless-udagram-app

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs8.10

  stage: ${opt:stage, 'dev'}

functions:
  GetGroups:
    handler: src/lambda/http/getGroups.handler
    events:
      -http:
        method: get
        path: groups
        cors: true